
print("\t\t\t\tFINAL INVOICE")
a=print("BED CHARGES:-")
b=int(input("multibed/simplebed:"))
c=print("diagnostics and investigations:-")
d=int(input("liver function test:"))
e=int(input("complete hemogram:"))
f=int(input("glucose random:"))
print("-"*65)
g=print("DOCTOR CHARGES:-")
h=int(input("doctor visit charges(1st visit):"))
i=int(input("doctor visit charges(2nd visit):"))
j=int(input("doctor visit charges(3rd visit):"))
print("-"*65)
k=print("DRUGS:-")
l=int(input("water for injection:"))
m=int(input("pantodac injection:"))
n=int(input("emeset injection:"))
o=int(input("DNS infusion:"))
p=int(input("pantodac infection:"))
import datetime
now=datetime.datetime.now()
dtm=str(now)
item=("item no.: 16")
price=b+d+e+f+h+i+j+l+m+n+o+p
print("-"*65)

print("-"*65)
print()
print("date:{0:>55s}".format(dtm))
print("-"*65)
print("item\t\t\tunit price\t")
print("-"*65)
print("{0:<25s}".format(item),end="")
print("{0:>7.2f}".format(price),end="")
print()
print("-"*65)
print("total:{0:>46.2f} Rs".format(price))
