print("DOCTOR'S RECORDS")
Doctor_ID=int(input("Enter doctor's ID :"))
print(Doctor_ID)
Name_of_doctor=input("Enter name of doctor :")
print(Name_of_doctor)
Father_husband_name=input("Enter doctor's father's or husband's name :")
print(Father_husband_name)
Gender=input("Enter the gender of doctor :")
print(Gender)
Department=input("Enter the department of doctor :")
print(Department)
Martial_status=input("Enter the doctor's martial status :")
print(Martial_status)
Consultation_Day=input("Enter consultation day of doctor :")
print(Consultation_Day)
Consultation_time_from=input("Consult from :")
print(Consultation_time_from)
Consultation_time_to=input("Consult to :")
print(Consultation_time_to)
Address=input("Enter doctor's address :")
print(Address)
Contact_no=int(input("Enter doctor's contact no :"))
print(Contact_no)
Emergency_no=int(input("Enter doctor's emergency no :"))
print(Emergency_no)
Age=int(input("Enter the doctor's age :"))
print(Age)
Total_pateints=int(input("Enter the number of pateints recovered :"))
print(Total_pateints)
Date_of_joining=input("Enter doctor's date of joining :")
print(Date_of_joining)
Assistant_doctor=input("Enter the name of doctor's assistant :")
print(Assistant_doctor)
Education=input("Enter doctor's education :")
print(Education)
Operation_days=input("Enter days doctor can operate :")
print(Operation_days)
Fee=int(input("Enter fee of doctor per month :"))
print(Fee)                             
print("STAFF RECORDS")
Staff_ID=int(input("Enter staff id :"))
print(Staff_ID)
Name_of_staff_member=input("Enter the name of staff :")
print(Name_of_staff_member)
Father_name=input("Enter the father's name of staff :")
print(Father_name)
Gender=input("Enter the gender of staff :")
print(Gender)
Phone_no=int(input("Enter staff's phone no :"))
print(Phone_no)
Doctor=input("Enter name of doctor under which staff works :")
print(Doctor)
Address=input("Enter the staff's address :")
print(Address)
Education=input("Enter the staff's education :")
print(Education)
Age=int(input("Enter the staff's age :"))
print(Age)
Fee=int(input("Enter the income of staff per month :"))
print(Fee)




                     
                     



               
