print("WELCOME TO HOSPITAL MANAGEMENT SYSTEM IN PYTHON")
ID=int(input("Enter the id of pateint :"))
print(ID)
Name=input("Enter the name of pateint :")
print(Name)
Father_name=input("Enter the name of pateint's father :")
print(Father_name)
Disease=input("Enter the name of disease pateint is suffering now :")
print(Disease)
Date_of_admission=input("Enter the date of admission :")
print(Date_of_admission)
Gender=input("Enter the gender of pateint :")
print(Gender)
Age=int(input("Enter the age of pateint :"))
print(Age)
Address=input("Enter the address of pateint :")
print(Address)
Phone_no=int(input("Enter the phone_no. of pateint :"))
print(Phone_no)
Date_of_birth=input("Enter the date of birth of pateint :")
print(Date_of_birth)
Pateint_current_medical_history=input("Enter the ancestral disease pateint is suffering from :")
print(Pateint_current_medical_history)
Blood_group=input("Enter the blood group of pateint :")
print(Blood_group)
Email=input("Enter the email :")
print(Email)
Tests_done=input("Enter the name of tests done :")
print(Tests_done)
Consultant=input("Enter doctor's name :")
print(Consultant)
Reference_doctor=input("Enter reference doctor's name :")
print(Reference_doctor)
Pateint_Type=input("Enter category of pateint :")
print(Pateint_Type)
Room_no=int(input("Enter room no. alloted to pateint :"))
print(Room_no)
Payment_method=input("Enter the mode of payment :")
print(Payment_method)





                    

